export const HA_NAM_COMMUNES = [
    "Xã Bình Lục",
    "Xã Bình Mỹ",
    "Xã Bình An",
    "Xã Bình Giang",
    "Xã Bình Sơn",
    "Xã Liêm Hà",
    "Xã Tân Thanh",
    "Xã Thanh Bình",
    "Xã Thanh Lâm",
    "Xã Thanh Liêm",
    "Xã Lý Nhân",
    "Xã Nam Xang",
    "Xã Bắc Lý",
    "Xã Vĩnh Trụ",
    "Xã Trần Thương",
    "Xã Nhân Hòa",
    "Xã Nam Lý",
    "Phường Duy Tiên",
    "Phường Duy Tân",
    "Phường Đồng Văn",
    "Phường Duy Hà",
    "Phường Tiên Sơn",
    "Phường Lê Hồ",
    "Phường Nguyễn Úy",
    "Phường Lý Thường Kiệt",
    "Phường Kim Thanh",
    "Phường Tam Chúc",
    "Phường Kim Bảng",
    "Phường Hà Nam",
    "Phường Phù Vân",
    "Phường Châu Sơn",
    "Phường Phủ Lý",
    "Phường Liêm Tuyền"
];
